import { sql, type Kysely } from "kysely";

/**
 * Security fix (money-path review §08 G): the audit hash-chain was ordered by
 * created_at = now() = transaction START time. Money-path audit rows are written
 * inside the outer money transaction, so a txn that started earlier can commit
 * (and append) later — ordering by created_at then forks the chain and makes
 * verifyChain() report false tampering.
 *
 * Fix: a monotonic append-order sequence. Using GENERATED ... AS IDENTITY means
 * Postgres fills existing rows with sequence values on ADD COLUMN and enforces
 * NOT NULL atomically (no backfill race with concurrent writers). Combined with
 * the existing advisory lock in AuditService (which serializes the append
 * critical section), `seq` reflects true append order and the chain is stable.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  // Idempotent against a prior partial run.
  await sql`ALTER TABLE audit_logs DROP COLUMN IF EXISTS seq`.execute(db);
  await sql`DROP SEQUENCE IF EXISTS audit_logs_seq`.execute(db);

  await sql`ALTER TABLE audit_logs ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY`.execute(db);
  await sql`CREATE UNIQUE INDEX audit_logs_seq_idx ON audit_logs (seq)`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP INDEX IF EXISTS audit_logs_seq_idx`.execute(db);
  await sql`ALTER TABLE audit_logs DROP COLUMN IF EXISTS seq`.execute(db);
}
